// Extended content for the eco multi-page site

const ECO_TEAM = [
  {
    name: 'Alex Oudin',
    role: 'Fondateur · Auditeur certifié',
    bio: "Ingénieur thermicien depuis plus de 10 ans. Certifié OPQIBI, RGE et Mon Accompagnateur Rénov', Alex réalise personnellement chaque diagnostic sur le terrain — sans déléguer, sans sous-traitance. Du premier rendez-vous jusqu'à la réception des travaux, vous n'avez qu'un seul interlocuteur.",
    badges: ['OPQIBI', 'RGE', 'MAR'],
    photo: 'images/alex-inspection.png',
  },
];

const ECO_CASES = [
  {
    id: 'pont-a-mousson',
    type: 'Pavillon 1972',
    location: 'Pont-à-Mousson',
    surface: '138 m²',
    before: { letter: 'G', kwh: 481, color: '#e3211c' },
    after: { letter: 'C', kwh: 148, color: '#bbcf3a' },
    savings: '1 743 €/an',
    aides: '28 400 €',
    rest: '7 100 €',
    works: ['Isolation combles + murs ITE', 'Pompe à chaleur air/eau', 'VMC double-flux', 'Menuiseries triple vitrage'],
    duration: '4 mois',
    quote: "On savait qu'il fallait faire des travaux, mais on n'imaginait pas qu'on pouvait passer de G à C en un seul chantier.",
    client: 'Famille Bertrand',
  },
  {
    id: 'luneville',
    type: 'Maison de ville 1910',
    location: 'Lunéville',
    surface: '95 m²',
    before: { letter: 'F', kwh: 362, color: '#ed7d31' },
    after: { letter: 'D', kwh: 218, color: '#fdee00' },
    savings: '980 €/an',
    aides: '14 600 €',
    rest: '5 800 €',
    works: ['Isolation toiture sous rampants', 'Chaudière à granulés', 'Remplacement fenêtres'],
    duration: '6 semaines',
    quote: "Le rapport d'audit était limpide. On a choisi le scénario médian, et on a obtenu plus d'aides que prévu.",
    client: 'Sophie & Marc',
  },
  {
    id: 'nancy-appt',
    type: 'Appartement haussmannien',
    location: 'Nancy · centre',
    surface: '78 m²',
    before: { letter: 'E', kwh: 287, color: '#fab627' },
    after: { letter: 'B', kwh: 92, color: '#52b757' },
    savings: '620 €/an',
    aides: '8 200 €',
    rest: '3 100 €',
    works: ['Isolation par l\'intérieur', 'Pompe à chaleur air/air', 'Remplacement menuiseries'],
    duration: '3 semaines',
    quote: "Diag Renov a fait toutes les démarches en copropriété. On a juste eu à signer.",
    client: 'Lucas',
  },
];

const ECO_FAQ = [
  {
    q: 'Combien coûte un DPE ?',
    a: 'Entre 150 € et 280 € selon la surface et la complexité du logement. Le tarif est fixé au devis après une rapide visite ou un échange téléphonique.',
  },
  {
    q: 'Combien de temps est valable un DPE ?',
    a: 'Les DPE réalisés depuis le 1ᵉʳ juillet 2021 sont valables 10 ans. Les DPE antérieurs ont une validité plus courte ou sont déjà obsolètes.',
  },
  {
    q: "Quelle est la différence entre un DPE et un audit énergétique ?",
    a: "Le DPE est une évaluation rapide (1h sur site, classement A-G). L'audit est plus poussé (2-3h, scénarios de travaux chiffrés, simulation des aides). L'audit est obligatoire à la vente d'un logement F ou G depuis 2023.",
  },
  {
    q: "Pourquoi faut-il passer par un Accompagnateur Rénov' ?",
    a: "C'est obligatoire pour bénéficier de MaPrimeRénov' Ampleur (la prime pour les rénovations globales). En contrepartie, l'État prend en charge jusqu'à 2 000 € de la prestation d'accompagnement.",
  },
  {
    q: 'Êtes-vous indépendants vis-à-vis des artisans ?',
    a: "Oui, totalement. Nous n'avons aucun lien commercial, aucune commission, aucun partenariat exclusif avec un fabricant ou un installateur. Notre rôle est de vous conseiller objectivement.",
  },
  {
    q: 'Sur quel périmètre intervenez-vous ?',
    a: "Sur toute la Meurthe-et-Moselle (département 54). Le premier déplacement est gratuit dans un rayon de 60 km autour de Nancy. Au-delà, des frais kilométriques sont précisés au devis.",
  },
  {
    q: "Sous quel délai recevez-vous le rapport ?",
    a: "DPE : sous 48h après la visite. Audit énergétique : sous 10 jours ouvrés. Études PV et chauffage : sous 15 jours ouvrés.",
  },
  {
    q: "Que se passe-t-il si je ne fais pas de travaux après l'audit ?",
    a: "Rien — l'audit est un outil de décision. Le rapport reste valable et utile à la revente. Aucune obligation d'engager des travaux derrière.",
  },
];

const ECO_VALUES = [
  {
    title: "Indépendance totale",
    desc: "Pas de commission, pas de partenaire artisan exclusif, pas de fabricant qui nous paie. Nos recommandations sont nos seuls comptes à rendre.",
  },
  {
    title: "Mesure plutôt qu'opinion",
    desc: "Chaque diagnostic s'appuie sur des relevés normés (3CL-2021, Th-BCE), pas sur un coup d'œil ou un avis personnel. Nos rapports sont sourcés.",
  },
  {
    title: "Pédagogie d'abord",
    desc: "Nos rapports sont écrits pour être lus par un propriétaire — pas par un bureau d'études. Schémas, chiffres et arbitrages clairs.",
  },
  {
    title: "Accompagnement long",
    desc: "On ne disparaît pas après la remise du rapport. Choix des artisans, dossiers d'aides, réception des travaux : on reste avec vous.",
  },
];

const ECO_DELIVERABLES_AUDIT = [
  { title: "Analyse de l'enveloppe", items: ['Murs, toiture, plancher bas', 'Menuiseries et ponts thermiques', 'Calcul des U-values', 'Identification des points faibles'] },
  { title: "État des équipements", items: ['Chauffage, ECS, ventilation', 'Calcul des rendements', 'Estimation de durée de vie', 'Risques en cas de défaillance'] },
  { title: "Scénarios chiffrés", items: ['3 scénarios de rénovation', 'Coûts HT et TTC détaillés', 'Économies d\'énergie attendues', 'Retour sur investissement'] },
  { title: "Plan d'aides", items: ['MaPrimeRénov\' & Ampleur', 'CEE et Éco-PTZ', 'Simulation reste à charge', 'Calendrier de versement'] },
];

const ECO_BLOG_POSTS = [
  {
    slug: 'bienvenue-diag-renov-immo',
    cat: 'À propos',
    date: 'Janvier 2026',
    readTime: '3 min',
    image: 'images/alex-inspection.png',
    title: 'Bienvenue chez Diag Renov Immo !',
    excerpt: "Passionnés par la transition énergétique, notre mission est de vous accompagner vers une consommation d'énergie plus responsable, économique, et confortable.",
    content: [
      { type: 'p', text: "Chez Diag Renov Immo, nous sommes passionnés par la transition énergétique et l'optimisation de la consommation d'énergie. Notre mission est de vous accompagner vers une utilisation plus responsable et économique de l'énergie, tout en améliorant votre confort thermique." },
      { type: 'h2', text: 'Nos Services' },
      { type: 'ul', items: [
        "Audits Énergétiques : diagnostics complets pour identifier les sources de déperdition d'énergie et proposer des solutions adaptées.",
        "Conseil et Stratégie Énergétique : plans d'action personnalisés pour réduire votre consommation et vos coûts.",
        "Installation et Maintenance : solutions de chauffage, climatisation et isolation pour une performance optimale.",
        "Suivi et Optimisation : suivi continu des performances et propositions d'améliorations en temps réel.",
      ]},
      { type: 'h2', text: "Pourquoi Choisir Diag Renov Immo ?" },
      { type: 'ul', items: [
        "Expertise : une équipe de professionnels certifiés et expérimentés.",
        "Innovation : utilisation des dernières technologies pour des solutions durables et performantes.",
        "Proximité : un accompagnement personnalisé et un service client réactif.",
        "Engagement : une démarche éco-responsable pour un avenir plus vert.",
      ]},
      { type: 'p', text: "Suivez-nous pour découvrir des astuces, des conseils et les dernières actualités en matière d'efficacité énergétique. Ensemble, faisons un pas vers un monde plus durable." },
    ],
  },
  {
    slug: 'mon-accompagnateur-renov-agrement',
    cat: 'Aides',
    date: 'Janvier 2026',
    readTime: '2 min',
    image: 'images/mar-agrement.png',
    title: "Diag Renov Immo obtient l'agrément Mon Accompagnateur Rénov'",
    excerpt: "Diag Renov Immo est désormais agréé Mon Accompagnateur Rénov' sur l'ensemble de la Meurthe-et-Moselle — une étape clé pour vous accompagner dans vos projets de rénovation.",
    content: [
      { type: 'p', text: "Nous sommes heureux de vous annoncer que Diag Renov Immo est désormais agréé Mon Accompagnateur Rénov' sur l'ensemble de la Meurthe-et-Moselle !" },
      { type: 'h2', text: "Qu'est-ce que cela signifie ?" },
      { type: 'p', text: "En tant que Mon Accompagnateur Rénov', Diag Renov Immo est à vos côtés pour vous guider dans tous vos projets de rénovation énergétique. Nous vous offrons un accompagnement sur mesure, de l'audit initial à la réalisation des travaux, en passant par les démarches administratives et l'obtention des aides financières." },
      { type: 'p', text: "Vous souhaitez en savoir plus ou commencer votre projet de rénovation ? Contactez Alex de Diag Renov Immo dès aujourd'hui." },
    ],
  },
  {
    slug: 'mon-accompagnateur-renov-avantages',
    cat: 'Aides',
    date: 'Janvier 2026',
    readTime: '5 min',
    image: 'images/accompagnateur-renov.png',
    title: "Comment un Mon Accompagnateur Rénov' transforme votre rénovation",
    excerpt: "Expertise sur mesure, soutien administratif, jusqu'à 90 % de subventions : voici pourquoi passer par un Accompagnateur Rénov' change tout à votre projet.",
    content: [
      { type: 'p', text: "Vous avez des projets de rénovation énergétique pour votre maison ? Saviez-vous que faire appel à un Mon Accompagnateur Rénov' peut vraiment changer la donne ?" },
      { type: 'h2', text: "Les avantages clés" },
      { type: 'ul', items: [
        "Expertise sur mesure : un pro à vos côtés pour évaluer vos besoins, vous proposer des solutions adaptées, et maximiser l'efficacité énergétique de votre maison.",
        "Soutien administratif : aide complète pour naviguer dans toutes les démarches et obtenir les aides financières disponibles.",
        "Financement jusqu'à 90 % : certaines subventions peuvent couvrir jusqu'à 90 % du montant HT des travaux, grâce à MaPrimeRénov', l'éco-prêt à taux zéro, et plus encore.",
        "Coût pris en charge : la prestation d'un Mon Accompagnateur Rénov' peut être financée jusqu'à 2 000 € par l'État.",
        "Sérénité garantie : de l'étude initiale à la fin des travaux, un accompagnement complet pour que tout se passe dans les meilleures conditions.",
        "Valorisation de votre bien : améliorer la performance énergétique, c'est aussi augmenter la valeur de votre maison.",
      ]},
      { type: 'p', text: "Passez à l'action pour réduire vos factures et faire un geste pour la planète !" },
    ],
  },
  {
    slug: 'rentabilite-chauffage',
    cat: 'Chauffage',
    date: 'Février 2026',
    readTime: '3 min',
    image: 'images/technicien-chauffage.png',
    title: "Rentabilité du chauffage : un enjeu majeur pour votre confort et votre budget",
    excerpt: "Avec les prix de l'énergie qui grimpent, réfléchir à la rentabilité de son système de chauffage peut faire toute la différence — en économies et en confort.",
    content: [
      { type: 'p', text: "Avec l'hiver qui approche et les prix de l'énergie qui grimpent, il est crucial de réfléchir à la rentabilité de votre système de chauffage. Voici pourquoi cela peut faire toute la différence :" },
      { type: 'h2', text: "Qu'est-ce que la rentabilité du chauffage ?" },
      { type: 'p', text: "La rentabilité du chauffage désigne l'efficacité avec laquelle votre système utilise l'énergie pour chauffer votre maison tout en gardant les coûts au minimum. Il s'agit de maximiser la performance tout en réduisant les dépenses." },
      { type: 'h2', text: "Pourquoi c'est important ?" },
      { type: 'ul', items: [
        "Économies d'Argent : un système performant réduit vos factures. En choisissant des solutions modernes et écoénergétiques, vous économisez sur le long terme.",
        "Confort Amélioré : un chauffage efficace assure une température agréable et stable dans toute la maison, tout en consommant moins.",
        "Valorisation de la Maison : des systèmes efficaces augmentent la valeur de votre bien immobilier.",
        "Respect de l'Environnement : améliorer l'efficacité de votre chauffage réduit votre empreinte carbone.",
      ]},
      { type: 'p', text: "Investir dans la rentabilité de votre chauffage, c'est opter pour un confort durable, des économies substantielles et une planète plus verte." },
    ],
  },
  {
    slug: 'etude-pv-chauffage-personnalisee',
    cat: 'Solaire & Chauffage',
    date: 'Février 2026',
    readTime: '4 min',
    image: 'images/panneaux-solaires-grosplan.png',
    title: "Études PV et chauffage personnalisées : optimisez votre énergie",
    excerpt: "Évaluez le potentiel de votre toiture et identifiez le système de chauffage le plus efficace pour votre maison, grâce à une étude sur mesure.",
    content: [
      { type: 'p', text: "Vous envisagez de passer aux énergies renouvelables ou d'améliorer votre système de chauffage ? Découvrez comment nos études personnalisées en panneaux photovoltaïques et en chauffage peuvent transformer votre maison et réduire vos factures énergétiques." },
      { type: 'h2', text: "Pourquoi réaliser une étude PV ou chauffage ?" },
      { type: 'p', text: "Une étude personnalisée vous permet de :" },
      { type: 'ul', items: [
        "Évaluer le potentiel de votre toiture pour l'installation de panneaux solaires.",
        "Identifier le système de chauffage le plus efficace et économique pour votre maison.",
        "Maximiser les économies d'énergie tout en augmentant votre confort.",
        "Bénéficier des aides et subventions disponibles pour la transition énergétique.",
      ]},
      { type: 'h2', text: "Les avantages sont nombreux" },
      { type: 'ul', items: [
        "Réduction significative des coûts énergétiques",
        "Contribution à la protection de l'environnement",
        "Augmentation de la valeur de votre bien immobilier",
        "Autonomie énergétique grâce aux énergies renouvelables",
      ]},
      { type: 'p', text: "Contactez-nous dès aujourd'hui pour une étude PV ou chauffage personnalisée et découvrez comment vous pouvez rendre votre maison plus verte et plus économique !" },
    ],
  },
  {
    slug: 'etude-photovoltaique-important',
    cat: 'Solaire',
    date: 'Mars 2026',
    readTime: '4 min',
    image: 'images/panneaux-solaires-toiture.png',
    title: "Panneaux photovoltaïques : pourquoi une étude préalable est indispensable",
    excerpt: "Avant d'installer des panneaux solaires, une étude approfondie garantit la performance maximale, la rentabilité et la conformité réglementaire de votre installation.",
    content: [
      { type: 'p', text: "L'énergie solaire est une solution prometteuse pour réduire notre empreinte carbone et nos factures d'électricité. Mais avant d'installer des panneaux photovoltaïques, une étude approfondie est essentielle. Voici pourquoi :" },
      { type: 'h2', text: "Qu'est-ce qu'une étude de panneaux photovoltaïques ?" },
      { type: 'p', text: "C'est une analyse complète qui examine la faisabilité de l'installation sur votre toit. Elle prend en compte l'ensoleillement, les ombrages possibles, l'orientation du toit et bien plus encore." },
      { type: 'h2', text: "Pourquoi c'est important ?" },
      { type: 'ul', items: [
        "Performance Maximale : une étude garantit que vos panneaux sont installés de façon à capter le maximum d'énergie solaire.",
        "Économies et Rentabilité : elle permet d'estimer les économies d'énergie et de calculer le retour sur investissement.",
        "Respect des Régulations : assure que votre projet est conforme aux normes locales en matière d'urbanisme et d'environnement.",
        "Bénéfices Écologiques : réduisez votre empreinte carbone et participez à la transition vers les énergies renouvelables.",
      ]},
      { type: 'p', text: "Investir dans une étude de panneaux photovoltaïques, c'est se tourner vers un avenir plus vert et plus économique. Prêt à franchir le pas ?" },
    ],
  },
  {
    slug: 'audit-energetique-valeur-maison',
    cat: 'Audit',
    date: 'Mars 2026',
    readTime: '5 min',
    image: 'images/alex-audit.png',
    title: "Audit énergétique : améliorez la valeur et le confort de votre maison",
    excerpt: "Avant de vendre ou de rénover, un audit énergétique est l'étape clé pour maximiser la valeur de votre bien et optimiser votre consommation d'énergie.",
    content: [
      { type: 'p', text: "Vous envisagez de vendre votre maison ou de réaliser des travaux pour améliorer votre confort ? Un audit énergétique est une étape essentielle pour maximiser la valeur de votre bien et optimiser votre consommation d'énergie." },
      { type: 'h2', text: "Qu'est-ce qu'un audit énergétique ?" },
      { type: 'p', text: "Un audit énergétique est une analyse approfondie de la performance énergétique de votre maison. Il identifie les sources de déperdition d'énergie et propose des solutions concrètes pour améliorer l'efficacité énergétique de votre habitation." },
      { type: 'h2', text: "Pourquoi réaliser un audit énergétique ?" },
      { type: 'ul', items: [
        "Valorisation Immobilière : un audit peut significativement augmenter la valeur de votre maison en améliorant son classement énergétique.",
        "Économies sur les Factures : en identifiant les zones de perte d'énergie et en appliquant les recommandations, vous réduisez considérablement vos factures.",
        "Amélioration du Confort : un logement bien isolé offre un confort optimal tout au long de l'année.",
        "Planification de Travaux : priorisez les actions à entreprendre pour un impact maximal avant de lancer vos travaux.",
      ]},
      { type: 'h2', text: "Comment ça fonctionne ?" },
      { type: 'ul', items: [
        "Inspection Détaillée : un expert certifié se rend chez vous pour une analyse complète avec des outils spécialisés.",
        "Rapport Complet : vous recevez un rapport détaillé avec des recommandations claires et pratiques.",
        "Accompagnement Personnalisé : nous vous guidons dans la mise en œuvre, des petits ajustements aux travaux importants.",
      ]},
    ],
  },
  {
    slug: 'dpe-diag-renov-immo',
    cat: 'DPE',
    date: 'Avril 2026',
    readTime: '3 min',
    image: 'images/dpe-document.png',
    title: "Diag Renov Immo réalise vos Diagnostics de Performance Énergétique",
    excerpt: "Vous avez un projet de vente ou de location ? Faites appel à Diag Renov Immo pour un DPE fiable, professionnel, et remis sous 48h.",
    content: [
      { type: 'p', text: "Vous avez un projet de vente ou de location de votre bien immobilier ? Faites appel à Diag Renov Immo pour un Diagnostic de Performance Énergétique (DPE) fiable et professionnel !" },
      { type: 'h2', text: "Pourquoi un DPE est-il important ?" },
      { type: 'ul', items: [
        "Obligation légale : un DPE est indispensable pour toute transaction immobilière.",
        "Valorisation de votre bien : un bon DPE peut augmenter la valeur de votre logement.",
        "Économies d'énergie : identifiez les améliorations possibles pour réduire votre consommation.",
        "Respect de l'environnement : contribuez à la protection de notre planète en optimisant la performance énergétique de votre habitation.",
      ]},
      { type: 'h2', text: "Pourquoi choisir Diag Renov Immo ?" },
      { type: 'ul', items: [
        "Expertise certifiée",
        "Rapport détaillé et compréhensible",
        "Conseils personnalisés pour améliorer l'efficacité énergétique de votre bien",
        "Intervention rapide — rapport remis sous 48h",
      ]},
      { type: 'h2', text: "Témoignages de nos clients" },
      { type: 'p', text: '"Le DPE réalisé par Diag Renov Immo a été très précis et m\'a permis de mieux comprendre les performances énergétiques de ma maison." — Lucas' },
      { type: 'p', text: '"Service impeccable et conseils avisés, je recommande vivement Diag Renov Immo !" — Marie' },
    ],
  },
  {
    slug: 'comprendre-le-dpe',
    cat: 'DPE',
    date: 'Avril 2026',
    readTime: '4 min',
    image: 'images/dpe-document.png',
    title: "Qu'est-ce qu'un DPE et pourquoi est-ce si important ?",
    excerpt: "Le DPE classe votre logement de A à G selon sa consommation énergétique. Un outil essentiel pour comprendre votre bien, sa valeur, et vos factures.",
    content: [
      { type: 'p', text: "Le Diagnostic de Performance Énergétique (DPE) est un outil clé pour comprendre la consommation énergétique de votre logement et son impact environnemental." },
      { type: 'h2', text: "Qu'est-ce qu'un DPE ?" },
      { type: 'p', text: "Le DPE est une évaluation qui classe un bâtiment selon sa consommation d'énergie, de A (très performant) à G (peu performant). Il prend en compte des éléments comme l'isolation, le chauffage, et la ventilation." },
      { type: 'h2', text: "Pourquoi c'est important ?" },
      { type: 'ul', items: [
        "Transparence pour les Acheteurs et Locataires : le DPE donne une vision claire de la performance énergétique, aidant à prendre des décisions informées.",
        "Valorisation de votre Bien : un bon DPE peut augmenter la valeur de votre maison ou appartement.",
        "Économies d'Énergie : identifier les faiblesses énergétiques permet de réaliser des travaux ciblés pour réduire vos factures.",
        "Environnement : améliorer la performance énergétique de votre logement réduit les émissions de gaz à effet de serre.",
      ]},
      { type: 'p', text: "En somme, le DPE est un outil essentiel pour une gestion plus écologique et économique de votre habitat. Pensez-y lors de vos projets immobiliers et faites appel à Diag Renov Immo pour vous accompagner !" },
    ],
  },
  {
    slug: 'passoires-energetiques-france',
    cat: 'Réglementation',
    date: 'Avril 2026',
    readTime: '5 min',
    image: 'images/dpe-document.png',
    title: "Passoires énergétiques : 4,8 millions de logements à rénover en France",
    excerpt: "Logements classés F et G, interdictions de location, MaPrimeRénov' Ampleur : tout ce que les propriétaires doivent savoir pour anticiper et agir.",
    content: [
      { type: 'p', text: "En France, plus de 4,8 millions de logements sont classés comme «passoires énergétiques». Ces habitations, mal isolées, consomment énormément d'énergie pour être chauffées et ont un impact direct sur la facture des ménages — et sur l'environnement. Le terme désigne les logements classés F ou G dans le diagnostic de performance énergétique (DPE)." },
      { type: 'h2', text: "Pourquoi rénover votre bien ?" },
      { type: 'ul', items: [
        "Réduction des factures : une meilleure isolation et un chauffage plus performant réduisent considérablement les dépenses énergétiques.",
        "Valorisation du patrimoine : un bien rénové augmente sa valeur sur le marché immobilier, les acheteurs étant de plus en plus sensibles à l'efficacité énergétique.",
        "Respect des nouvelles lois : depuis 2025, les logements classés G ne peuvent plus être loués. Ce seuil sera progressivement abaissé, rendant la rénovation obligatoire avant 2028 pour les F.",
        "Impact environnemental : en rénovant, vous contribuez activement à la lutte contre le réchauffement climatique en réduisant vos émissions de CO₂.",
      ]},
      { type: 'h2', text: "Les aides disponibles" },
      { type: 'p', text: "L'État met en place plusieurs dispositifs pour vous aider à financer vos travaux, parmi lesquels la nouvelle subvention MaPrimeRénov' Ampleur. Cette aide est conçue pour les projets de rénovation globale — ceux qui visent à améliorer significativement les performances énergétiques en réalisant plusieurs types de travaux en même temps. Elle peut couvrir une grande partie des dépenses, notamment pour les ménages modestes." },
      { type: 'ul', items: [
        "MaPrimeRénov' Ampleur : jusqu'à 90 % des travaux pour les ménages modestes",
        "Certificats d'Économie d'Énergie (CEE) : prime versée par les fournisseurs d'énergie",
        "Éco-PTZ : prêt à taux zéro jusqu'à 50 000 €",
        "Mon Accompagnateur Rénov' : prise en charge jusqu'à 2 000 € de l'accompagnement",
      ]},
      { type: 'h2', text: "Vous avez un projet de rénovation ?" },
      { type: 'p', text: "Pour avancer dans vos travaux et bénéficier d'un accompagnement personnalisé, contactez Diag Renov Immo. Nous sommes là pour vous guider dans votre démarche : Email : diagrenovimmo@gmail.com — Téléphone : 07 49 13 79 11." },
    ],
  },
];

window.ECO_DATA = {
  TEAM: ECO_TEAM,
  CASES: ECO_CASES,
  FAQ: ECO_FAQ,
  VALUES: ECO_VALUES,
  DELIVERABLES_AUDIT: ECO_DELIVERABLES_AUDIT,
  BLOG_POSTS: ECO_BLOG_POSTS,
};
